
- name: Create nextcloud service directory
  file:
    path: "{{ nextcloud_install_dir }}/{{ item.name }}"
    state: directory
    owner: "{{ depl_user }}"
    mode: 0755
  register: nextcloud_directory_stat

- name: Create nextcloud volumes
  file:
    path: "{{ nextcloud_volumes_dir }}/{{ dir_item }}"
    state: directory
    owner: "{{ depl_user }}"
    mode: 0755
  with_items:
    - "{{ item.name }}"
    - "{{ item.name }}-db"
  loop_control:
    loop_var: dir_item

- name: Debug 
  ansible.builtin.debug:
    msg:
    - "Deploying a nextcloud in {{ nextcloud_directory_stat.path }}"

- name: Copy Web Dockerfile
  copy:
    src: web
    dest: "{{ nextcloud_directory_stat.path }}"
    owner: "{{ depl_user }}"
    mode: 0644

- name: Generate all files
  template:
    src: "{{ index_file.src }}"
    dest: "{{ nextcloud_directory_stat.path }}/{{ index_file.dest }}"
    owner: "{{ depl_user }}"
    group: "{{ depl_group }}"
    mode: 0644
  with_items:
    - { src: 'dotenv.j2', dest: '.env' }
    - { src: 'db.env.j2', dest: 'db.env' }
    - { src: 'docker-compose.yml.j2', dest: 'docker-compose.yml' }
    - { src: 'nginx.conf.j2', dest: 'web/nginx.conf' }
  loop_control:
    loop_var: index_file

